[project]
name = "django-workspace"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django==4.2.2",
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.7.0",
    "mysqlclient>=2.2.7",
    "pydantic-settings>=2.11.0",
]

[dependency-groups]
dev = [
    "pyright>=1.1.406",
    "ruff>=0.13.3",
    "taskipy>=1.14.1",
]

[tool.taskipy.tasks]
fmt = "ruff check --fix && ruff format"
type = "pyright"
dev = "python django_project/manage.py runserver"
manage = "python django_project/manage.py"
docs = "mkdocs serve --dev-addr localhost:3000"
db = "python django_project/manage.py dbshell"
